[build]
  command = "npm install"
  functions = "functions" 
  publish = "public"

[dev]
  port = 8888
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/user/*"
  to = "/user/index.html"
  status = 200

[[redirects]]
  from = "/page.html"
  to = "/page.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
